### PR TITLE
Added the ability to set the background color

### PR DESCRIPTION
**Pull request by PGMacDesign**
Added 2 methods for setting the background color of the Elastic view. It should take in either an int color or a String and parse the color. If the string is null or the parsing fails, nothing will be set and it will retain the original color

I created a pull request into the bugfix branch (not master) so you can update after testing if you would like. I tested it myself before pushing and it seems to have no issues that I can find.

### CODE REVIEW

**Comment by Tibolte** [comment]
You're doing a PR into the wrong branch, don't target _restore_state_ but _master_. That reminds me I have to delete this old branch :)

**Comment by PGMacDesign** [comment]
Ha. Apologies, I'll make a pull request to master

**Comment by PGMacDesign** [comment]
Updated with new pull:
https://github.com/Tibolte/ElasticDownload/pull/35
Thanks!

**Comment by PGMacDesign** [comment]
I see that the merge went through, but it looks like the gadle / maven builds are still the old version. Any chance you could update the file whenever you have some free time? Thanks!

**Comment by Tibolte** [comment]
Yes good point I'll try to do that asap and publish a new version.

**Pull request closed without merging**
