### PR TITLE
Revert "Paths animation"

### PR DESCRIPTION
**Pull request by AronI**
Reverts Tibolte/ProgressDownload#1

### CODE REVIEW

**Comment by Tibolte** [comment]
Tell me why do you wanna revert?

**Comment by AronI** [comment]
Lol sry bro I did a mistake

**Comment by AronI** [comment]
Just discard it, I thought I merged a branch with no commits. Was going to
revert that.

**Comment by Tibolte** [comment]
No pb, I'll just close it.

**Pull request closed without merging**
